! CSC 408 PROGRAMMING LANGUAGES
! PROGRAM: STUDENT TEST SCORE ANALYZER
! PROGRAMMER: TARBI PYAKUREL
! USM ID: W10172900
! DATE: 03/05/2026
! DESCRIPTION:  THIS PROGRAM IS DESIGNED TO READ THE TOTAL NUMBER OF SCORES TO BE ENTERED
!               AND EACH INDIVIDUAL SCORES. THEN IT DISPLAYS ALL THE INDIVIDUAL SCORES OF THE
!               STUDENTS. AFTER THAT IT CALCULATES THE AVERAGE SCORE, SUM OF ALL SCORES,
!               TOTAL STUDENTS THAT PASSED, TOTAL STUDENTS THAT FAILED, HIGHEST SCORE, LOWEST
!               SCORE. THEN IT DISPLAYS ALL OF THE CALCULATED VALUES ON THE SCREEN.
! REQUIREMENTS: FORTRAN IV COMPILER TO RUN IT. I USED GFORTRAN COMPILER SINCE I WAS USING ARM
!               BASED MACBOOK AND COULD NOT INSTALL INTEL'S COMPILER ON MY MACBOOK.
! DATA:         N=TOTAL NUMBER OF SCORES(TYPE-INTEGER)
!               I= INCREMENT VARIABLE(TYPE-INTEGER)
!               SCORES(20)= ARRAY OF 20 MAX LENGTH(TYPE-INTEGER)
!               PASS= TOTAL STUDENTS THAT PASSED(TYPE-INTEGER)
!               FAIL=TOTAL NUMBER OF STUDENTS THAT FAILED(TYPE-INTEGER)
!               HIGH=HIGHEST SCORE(TYPE-INTEGER)
!               LOW=LOWEST SCORE(TYPE-INTEGER)
!               AVG=AVERAGE SCORE(TYPE-REAL)
!               SUM=SUM OF ALL SCORES(TYPE-REAL)       
      
      PROGRAM TESTSCOREANALYZER

! VARIABLES DECLARATION AS FOLLOWS: INTEGER DATA TYPE  N=NUMBER OF TEST SCORES, SCORES= ARRAY OF UPTO 20 TEST SCORES, I=INCREMENT VAR>
! PASS= NUMBER OF PEOPLE WHO PASSED, FAIL=NO. OF PEOPLE WHO FAILED, HIGH= HIGH SCORE, LOW=LOW SCORE
      INTEGER N, I , SCORES(20), PASS, FAIL, HIGH, LOW
      
! VARIABLE DECLARATIONS: REAL DATA TYPE NUMBERS AVG=AVERAGE OF THE TEST SCORES, SUM=SUM OF ALL TEST SCORES
      REAL AVG,SUM

! DECLARE FORMAT FOR INPUT FOR OLDER FORTRAN VERSION
! CAN USE FORMAT WITH 4 INTEGER CHARACTERS FOR BOTH INPUT NUMBER OF SCORES 
 100  FORMAT(I4)
 

!     READ TOTAL NUMBER OF SCORES
      PRINT *,'ENTER NUMBER OF SCORES:'
      READ (5,100) N
      
! INITIALIZE VARIABLES
      SUM=0.0
      PASS=0
      FAIL=0
      
! READ SCORES INTO AN ARRAY AND CALCULATE PASS AND FAIL USING A DO LOOP TO REPEAT LINE NUMBER 10 STARTING FROM 1 TO N     
      DO 10 I=1, N
      PRINT *,'ENTER SCORES #', I
      READ (5,100) SCORES(I)
      
! ADD USER INPUT SCORES WITH TOTAL SUM
      SUM=SUM +FLOAT(SCORES(I))
      
! IF SCORE IS GREATER THAN OR EQUAL TO 60
      IF (SCORES(I) .GE. 60) PASS=PASS+1
      IF (SCORES(I) .LT. 60) FAIL=FAIL+1
 10   CONTINUE
      
! FIND HIGHEST AND LOWEST VALUE
! INITIALIZE HIGHEST AND LOWEST SCORES
      
      HIGH=-1000
      LOW=1000
      
! DO LINE NUMBER 20 FROM I=1 TO I=N AND REPLACE HIGH WITH THE HIGHEST AND LOW WITH THE LOWEST SCORES
      DO 20 I=1, N
      IF (SCORES(I) .GT. HIGH) HIGH=SCORES(I)
      IF (SCORES(I) .LT. LOW) LOW=SCORES(I)
      
 20   CONTINUE
! CALCULATE AVG BY DIVIDING SUM AND TOTAL NUMBER OF SCORES
      AVG=SUM/FLOAT(N)
      
! OUTPUT ALL THE RESULTS
      PRINT *, 'SCORES:'
      DO 30 I=1, N
      PRINT *, SCORES(I)
 30   CONTINUE
      
      PRINT *, 'AVERAGE = ', AVG
      PRINT *, 'HIGHEST = ', HIGH
      PRINT *, 'LOWEST = ', LOW
      PRINT *, 'PASSING = ',PASS
      PRINT *, 'FAILING = ', FAIL
      
      END

